[package]
name = "tool-process"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
app-core = { workspace = true }
tool-core = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
